version: '3.5'

services:
  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_STRIPE_PUBLIC_KEY: ${VITE_STRIPE_PUBLIC_KEY}
    networks:
      - basenet
    volumes:
      - '/app/node_modules'
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
networks:
  basenet:
    name: 'sessions-network'
